### PR TITLE
Upgrade to webpack 4

### PR DESCRIPTION
**Pull request by anajavi**
This upgrades webpack and some other libraries.

Also modifies babelrc to remove stage-0 preset.

This saves around 10kB on production bundle.

I was checking how difficult it would be to upgrade to react-leaflet@2.0.0-beta.1 when I noticed that the build could be improved too.

Edit: This now also builds ES modules too. And upgrades to babel@7
This allows people using webpack > 2 to save space.
lodash is replaced with lodash-es, the same that react-leaflet uses.
It also removes commonjs build.

### CODE REVIEW

**Comment by anajavi** [comment]
Shouldn't the main field in package.json be:
```
"main": "dist/react-leaflet-draw.min.js",
```
instead of:
```
"main": "dist/react-leaflet-draw.js", 
```

**Comment by anajavi** [comment]
This now builds 10kB minified UMD-build.

I'd like to add ES module build to this. The easiest way to do that would be to remove the commonjs build in lib/. I don't know what it is used for now.

It can be added without removing the build, but the babelrc then goes a little complex. 

@alex3165 would it be okay to remove the commonjs build? The ESM build would save even more space for people using modern bundlers like webpack 4.

**Comment by srghma** [comment]
@anajavi, your pr was merged and published to npm under version 0.19, tnx :)

**Comment by anajavi** [comment]
Nice, thanks! Was kind of expecting version 1.0.0 as it had breaking changes in peerDependencies.

**Comment by srghma** [comment]
@anajavi yes, I should, maybe next time

**Pull request merged**
