### PR TITLE
Upgrade to react 18

### LINKED ISSUE #139: Support React v18
React v18 has been released about three weeks ago: https://reactjs.org/blog/2022/03/29/react-v18.html

Leaflet and react-leaflet have already upgraded to support this new version. Are there plans to upgrade this package as well?

### LINKED ISSUE #144: react-leaflet v4 and React v18 (not supporting)
Please support for react-leaflet v4 and react version 18

### PR DESCRIPTION
**Pull request by brennanwilkes**
Upgrades react, react-dom, react-leaflet, leaflet, and leaflet-draw to modern versions.

Fixes a bug related to react useEffect tear-down  methods.

Closes #139 
Closes #144 
Addresses concerns in #145

### CODE REVIEW

**Comment by brennanwilkes** [comment]
Upgrades to webpack 5

**Comment by rbertucat** [comment]
Hi @alex3165, thanks for the great work you've put into that project. Would it be possible to have that branch approved/merged please?

**Comment by brennanwilkes** [comment]
This also fixes the issue in #140 as I thought it was caused by a modern node version, let me know if you’d like me to remove that fix from this PR so it doesn’t conflict with #140.

**Comment by brennanwilkes** [comment]
@rbertucat [Version 0.20.0](https://www.npmjs.com/package/react-leaflet-draw/v/0.20.0) Has this patch. Please let me know if there are any bugs or issues with it

**Pull request merged**
